### ISSUE TITLE
Firefox 46 noscript.js Error

### ISSUE THREAD

**Issue by VovaFreeman** [ervandew/vimperator-plugins#5]
Starting for the version 46, Firefox does not load noscript.js with the error:
Sourcing file failed:~\noscript.js:148:SyntaxError: missing ] after element list.

**Comment by roosemberth** [comment]
Same issue here

**Comment by VovaFreeman** [comment]
Hey, roosemberth!
I've fixed this issue and commited a pull request. It's pending approval, meanwhile you can find the fix in the "Patch-1" branch.

**Comment by roosemberth** [comment]
@VovaFreeman Thanks, I'll test tomorrow!
